# 統計学とは

ここでは統計学の基本的な考え方について説明する。

In [11]:
from sklearn.datasets import load_iris
data = load_iris()
print(data.data)
print(data.target)
print(data.target_names)
print(data.DESCR)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
from sklearn.datasets import load_wine
data = load_wine()
print(data.data)
print(data.target)
print(data.target_names)
print(data.DESCR)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
['class_0' 'class_1' 'class_2']
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric

In [13]:
from sklearn.datasets import load_boston
data = load_boston()
print(data.data)
print(data.target)
print(data.DESCR)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

## 変数の種類、尺度

データを構成する変数には大きく分けて

- 量的変数
- 質的変数

の二つがある。
これらの違いがどのような手法を選択するかに影響してくる。

また変数の尺度として

- 名義尺度
- 順序尺度
- 間隔尺度
- 比例尺度

がある。

## 記述統計と推測統計

記述統計とは、集団の特徴を記述するため、すべての個体を観測し、データを整理要約し把握するものである。
例えば

- 国勢調査
- 会社の健康診断結果
- スポーツの記録
- 顧客の購買履歴

などを整理することで、対象となる集団全体の観測結果を把握する。

推測統計とは、集団の一部のみを観察し、全体の様子を推測するものである。
例えば

- 選挙速報（出口調査）
- 新製品のアンケート調査
- 視聴率

などがある。

全数調査が可能出ない場合とはどのような場合だろうか？
- コスト
- 破壊検査
- 未来過去のこと

## 母集団と標本
調査対象として想定する集団全体を母集団、そのうち分析のために選ばれた一部を標本という。

標本調査の考え方
標本にはばらつきがあるが、それをできるだけ取り除かなくては正しい推測を行うことができない。また、母集団の傾向をできるだけ再現するように標本を得ることが必要である。
そのための考え方として

- ランダム化
- 層化抽出

がある。

実際には統計分析にはバイアスがつきものである。
例えば世論調査の結果が新聞によって違うのはなぜだろうか？

標本調査の結果は偶然の産物だが、
標本を取り替えると何が起こるのかを考えるのが推測統計の理論が目指すところである。
この偶然性について取り扱うために、確率の考え方を援用する。

In [1]:
import numpy as np

sample = np.random.normal(loc=170.0, scale=10.0, size=10)
np.mean(sample)

174.09835194106498

In [4]:
[np.mean(np.random.normal(loc=170.0, scale=10.0, size=1000000)) for i in range(5)]

[170.0159829301217,
 169.99527840565057,
 169.993840508512,
 170.0082616376247,
 169.99288405025678]

In [17]:
import numpy as np

total = np.random.normal(loc=170.0, scale=10.0, size=10000)
print(total)

[192.98962754 149.72362354 179.49835924 ... 175.58189502 162.78868388
 158.5702786 ]


In [18]:
np.mean(total)

169.9963584600155

In [23]:
sample = np.random.randint(0,10000,30)
print(total[sample])
print(np.mean(total[sample]))

[186.59913761 176.83104105 172.59225982 162.17031056 168.61274377
 159.33360211 160.2320891  196.72860143 168.94358443 173.20021202
 187.52436905 165.36982315 186.24371445 173.78911057 149.59671308
 152.51879787 167.42212088 147.70533028 162.44504064 172.46599053
 176.89649985 164.06694734 161.72839232 166.82407971 173.57461572
 171.90980034 173.50294276 176.27177902 177.3795762  167.20581743]
169.98950143730272


In [24]:
sample = np.random.randint(0,10000,30)
print(total[sample])
print(np.mean(total[sample]))

[179.51772927 174.10833309 163.99778376 146.5336419  156.53422123
 161.92947762 173.26854703 169.05595162 170.772297   176.15290686
 174.19623272 165.97417496 171.42915487 182.06546885 156.54241518
 158.34041248 173.15322615 179.57085284 187.41024707 187.40179686
 166.81523031 176.87971468 170.98265022 177.55554003 173.85457893
 162.63792523 184.89353272 157.91489007 192.78994256 177.55593133]
171.66116024805333


In [25]:
sample = np.random.randint(0,10000,30)
print(total[sample])
print(np.mean(total[sample]))

[167.46932683 170.8543793  190.80402988 165.60069493 145.14123892
 183.60903419 182.46217581 191.54147106 185.76883188 181.01223329
 177.03385318 156.31672517 166.11608272 166.92006693 137.10079617
 179.60787441 176.65277229 165.57125538 161.93560661 172.47203686
 187.28202309 180.07915637 177.36439986 179.23256206 175.77884935
 161.70573953 164.72971799 187.78818727 176.58200127 160.05137471]
172.486149910697


In [26]:
sample = np.random.randint(0,10000,30)
print(total[sample])
print(np.mean(total[sample]))

[171.01291358 179.28431688 179.27514643 180.2929343  169.90452751
 161.73717365 160.64083422 180.96168334 190.20669504 165.31481635
 172.14881095 159.45529082 182.67429757 157.31423664 174.79793135
 159.34628578 181.07894425 165.9685845  180.41315679 177.72134991
 165.19823758 164.45057477 174.05183657 178.92547502 175.66327131
 154.62089449 172.21476507 166.79145166 183.07874194 164.89036325]
171.64785138437477


## データのばらつき、分散

上で見たように標本にはばらつきが存在する。
そのようなばらつきを扱うための数値的な指標が分散である。

詳しくは後ほど説明するが、分散を調べることで集団の傾向を知ることができたり、予測の精度について議論することができる。
統計や機械学習において、最も重要な量といってもよい。

## 機械学習と統計

機械学習と統計の違いとして、よく言われることは機械学習は予測がメイン、統計は説明がメインというものである。

実際、機械学習の手法ではまずは予測精度を優先にして、なぜそれがうまくいくのかの説明は後回しというものがある。

一方で、機械学習の手法やその正当性を説明するための道具として統計学が用いられる。

## モデルと予測

統計学や機械学習では、データを説明し、また予測するために、モデルを作る。
モデルは確率分布の言葉を用いて記述されることが多いが、表面上はそのように見えない場合もよくある。

モデルにはパラメータがあり、データを用いてパラメータを決定する。

色々なモデルを比較し、どのモデルがよりよく予測することができるかを調べていくことが必要になる。

## 予測が合わない時の考え方

常識的な判断、あるいはあらかじめ立てた仮説に合わない結果が統計的に得られることはよくある。このようなときに、どう考えればよいか？

- 標本の偏り
- モデルが不十分
- 新しい変数を導入して、データの探索


Amazonの採用の例。
機械学習により採用を自動化したところ、女性が不利になる傾向が見られた。
この問題に対処するにはどのようにすればよいか？
- 性別という変数を無視するだけで十分か？

## 数学との関係

この講義で扱う数学は主に線形代数、微積分、確率の三つに分けられる。
これら数学的な内容と統計、機械学習の関係について簡単に説明する。

### 線形代数
機械学習では多変数のデータを扱うが多変数のデータを扱うための基本的な数学的な方法が線型代数である。
統計や機械学習に現れる様々な手法やその計算は、ベクトルや行列といった線形代数の言葉を用いて表される。

線形とは？
幾何的には直線や平面といったまっすぐなもののこと。
関数の言葉では比例や一次関数のような単純な関係のこと。
機械学習では線形な手法が最も基本的である。
直線的な関係であるため人間の直感が働きやすい。
例えば線形回帰、線形判別といった手法がある。

### 微積分
微分はものの変化を調べるための方法。
特になんらかの量が最大や最小になるのはどのようなときかを調べる。

例えばデータを分析し予測をするときに、どのような式を用いて予測すると最もよく予測できるか？という問いを立てよう。
このとき、その式を決めるため、誤差が最小になるのはいつかを微分を用いて求める。

微分で行うことは、複雑なものの変化の比率を調べることにより、物事を線形化して調べやすくするということである。

積分は面積や密度の分布から重さを求めるためのもの。
積分でやっていることは、平たく言えば足し算である。

確率について数学的に扱うために用いられる。

### 確率
不確定要素を含む標本から母集団について推測する必要がある。
この不確定要素を数学的に表現するために用いられるのが確率である。
確率分布を用いてモデルを作るという作業を行う。